swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Pool API
consumes:
  - application/json
produces:
  - application/json

paths:

  /tests/types:
    get:
      operationId: tests.get_types
      tags:
        - Tests
      summary: Get Test Types.
      description: Get all created types of tests sorted by testtypeid.
      responses:
        200:
          description: Successfully read Test Types table.
          schema:
            type: array
            items:
              properties:
                testtypeid:
                  type: integer
                  description: ID of the Test Type returned.
                test_name:
                  type: string
                  description: Name of the Test returned.
                  


